# Generated by Django 2.2.1 on 2019-05-10 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('difficulity', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Insane', 'Insane')], max_length=6)),
                ('duration', models.TimeField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Problem_Name', models.CharField(max_length=10)),
                ('statement', models.TextField()),
                ('solution', models.TextField()),
                ('solution_language', models.CharField(choices=[('py', 'Python'), ('cpp', 'C++'), ('c', 'C Language'), ('java', 'Java')], max_length=4)),
                ('Time_limit', models.DecimalField(decimal_places=3, max_digits=5)),
                ('Memory_limit', models.DecimalField(decimal_places=8, max_digits=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Input', models.TextField()),
                ('Output', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slogan', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.TextField()),
                ('Code_language', models.CharField(choices=[('py', 'Python'), ('cpp', 'C++'), ('c', 'C Language'), ('java', 'Java')], max_length=4)),
                ('Verdict', models.CharField(choices=[('ACC', 'Accepted'), ('TLE', 'Time Limit Exceeded'), ('WA', 'Wrong Answer'), ('MLE', 'Memory Limit Exceeded')], max_length=4)),
                ('Time', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=5, null=True)),
                ('Memory', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=5, null=True)),
                ('Score', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=5, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Contestant')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Problemset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('index', models.CharField(max_length=2)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem')),
            ],
            options={
                'ordering': ('contest', 'index'),
            },
        ),
        migrations.AddField(
            model_name='contestant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Team'),
        ),
    ]
